// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Compresses the given string with gzip and then encodes the result to base64.
func Base64gzip(ctx *pulumi.Context, args *Base64gzipArgs, opts ...pulumi.InvokeOption) (*Base64gzipResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv Base64gzipResult
	err := ctx.Invoke("std:index:base64gzip", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type Base64gzipArgs struct {
	Input string `pulumi:"input"`
}

type Base64gzipResult struct {
	Result string `pulumi:"result"`
}

func Base64gzipOutput(ctx *pulumi.Context, args Base64gzipOutputArgs, opts ...pulumi.InvokeOption) Base64gzipResultOutput {
	outputResult := pulumix.ApplyErr[*Base64gzipArgs](args.ToOutput(), func(plainArgs *Base64gzipArgs) (*Base64gzipResult, error) {
		return Base64gzip(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[Base64gzipResultOutput, *Base64gzipResult](outputResult)
}

type Base64gzipOutputArgs struct {
	Input pulumix.Input[string] `pulumi:"input"`
}

func (args Base64gzipOutputArgs) ToOutput() pulumix.Output[*Base64gzipArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *Base64gzipArgs {
		return &Base64gzipArgs{
			Input: resolvedArgs[0].(string),
		}
	})
}

type Base64gzipResultOutput struct{ *pulumi.OutputState }

func (Base64gzipResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Base64gzipResult)(nil)).Elem()
}

func (o Base64gzipResultOutput) ToOutput(context.Context) pulumix.Output[*Base64gzipResult] {
	return pulumix.Output[*Base64gzipResult]{
		OutputState: o.OutputState,
	}
}

func (o Base64gzipResultOutput) Result() pulumix.Output[string] {
	return pulumix.Apply[*Base64gzipResult](o, func(v *Base64gzipResult) string { return v.Result })
}
