// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Returns the first non-empty list from the given list of lists.
func Coalescelist(ctx *pulumi.Context, args *CoalescelistArgs, opts ...pulumi.InvokeOption) (*CoalescelistResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv CoalescelistResult
	err := ctx.Invoke("std:index:coalescelist", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type CoalescelistArgs struct {
	Input [][]interface{} `pulumi:"input"`
}

type CoalescelistResult struct {
	Result []interface{} `pulumi:"result"`
}

func CoalescelistOutput(ctx *pulumi.Context, args CoalescelistOutputArgs, opts ...pulumi.InvokeOption) CoalescelistResultOutput {
	outputResult := pulumix.ApplyErr[*CoalescelistArgs](args.ToOutput(), func(plainArgs *CoalescelistArgs) (*CoalescelistResult, error) {
		return Coalescelist(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[CoalescelistResultOutput, *CoalescelistResult](outputResult)
}

type CoalescelistOutputArgs struct {
	Input pulumix.Input[[][]interface{}] `pulumi:"input"`
}

func (args CoalescelistOutputArgs) ToOutput() pulumix.Output[*CoalescelistArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *CoalescelistArgs {
		return &CoalescelistArgs{
			Input: resolvedArgs[0].([][]interface{}),
		}
	})
}

type CoalescelistResultOutput struct{ *pulumi.OutputState }

func (CoalescelistResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CoalescelistResult)(nil)).Elem()
}

func (o CoalescelistResultOutput) ToOutput(context.Context) pulumix.Output[*CoalescelistResult] {
	return pulumix.Output[*CoalescelistResult]{
		OutputState: o.OutputState,
	}
}

func (o CoalescelistResultOutput) Result() pulumix.ArrayOutput[interface{}] {
	value := pulumix.Apply[*CoalescelistResult](o, func(v *CoalescelistResult) []interface{} { return v.Result })
	return pulumix.ArrayOutput[interface{}]{
		OutputState: value.OutputState,
	}
}
