// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Combines two or more lists into a single list.
func Concat(ctx *pulumi.Context, args *ConcatArgs, opts ...pulumi.InvokeOption) (*ConcatResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ConcatResult
	err := ctx.Invoke("std:index:concat", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ConcatArgs struct {
	Input [][]interface{} `pulumi:"input"`
}

type ConcatResult struct {
	Result []interface{} `pulumi:"result"`
}

func ConcatOutput(ctx *pulumi.Context, args ConcatOutputArgs, opts ...pulumi.InvokeOption) ConcatResultOutput {
	outputResult := pulumix.ApplyErr[*ConcatArgs](args.ToOutput(), func(plainArgs *ConcatArgs) (*ConcatResult, error) {
		return Concat(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[ConcatResultOutput, *ConcatResult](outputResult)
}

type ConcatOutputArgs struct {
	Input pulumix.Input[[][]interface{}] `pulumi:"input"`
}

func (args ConcatOutputArgs) ToOutput() pulumix.Output[*ConcatArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *ConcatArgs {
		return &ConcatArgs{
			Input: resolvedArgs[0].([][]interface{}),
		}
	})
}

type ConcatResultOutput struct{ *pulumi.OutputState }

func (ConcatResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ConcatResult)(nil)).Elem()
}

func (o ConcatResultOutput) ToOutput(context.Context) pulumix.Output[*ConcatResult] {
	return pulumix.Output[*ConcatResult]{
		OutputState: o.OutputState,
	}
}

func (o ConcatResultOutput) Result() pulumix.ArrayOutput[interface{}] {
	value := pulumix.Apply[*ConcatResult](o, func(v *ConcatResult) []interface{} { return v.Result })
	return pulumix.ArrayOutput[interface{}]{
		OutputState: value.OutputState,
	}
}
