// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Returns true if a list contains the given element and returns false otherwise.
func Contains(ctx *pulumi.Context, args *ContainsArgs, opts ...pulumi.InvokeOption) (*ContainsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ContainsResult
	err := ctx.Invoke("std:index:contains", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ContainsArgs struct {
	Element interface{}   `pulumi:"element"`
	Input   []interface{} `pulumi:"input"`
}

type ContainsResult struct {
	Result bool `pulumi:"result"`
}

func ContainsOutput(ctx *pulumi.Context, args ContainsOutputArgs, opts ...pulumi.InvokeOption) ContainsResultOutput {
	outputResult := pulumix.ApplyErr[*ContainsArgs](args.ToOutput(), func(plainArgs *ContainsArgs) (*ContainsResult, error) {
		return Contains(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[ContainsResultOutput, *ContainsResult](outputResult)
}

type ContainsOutputArgs struct {
	Element pulumix.Input[interface{}]   `pulumi:"element"`
	Input   pulumix.Input[[]interface{}] `pulumi:"input"`
}

func (args ContainsOutputArgs) ToOutput() pulumix.Output[*ContainsArgs] {
	allArgs := pulumix.All(
		args.Element.ToOutput(context.Background()).AsAny(),
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *ContainsArgs {
		return &ContainsArgs{
			Element: resolvedArgs[0].(interface{}),
			Input:   resolvedArgs[1].([]interface{}),
		}
	})
}

type ContainsResultOutput struct{ *pulumi.OutputState }

func (ContainsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ContainsResult)(nil)).Elem()
}

func (o ContainsResultOutput) ToOutput(context.Context) pulumix.Output[*ContainsResult] {
	return pulumix.Output[*ContainsResult]{
		OutputState: o.OutputState,
	}
}

func (o ContainsResultOutput) Result() pulumix.Output[bool] {
	return pulumix.Apply[*ContainsResult](o, func(v *ContainsResult) bool { return v.Result })
}
