// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Reads the contents of a file into a string and returns the SHA512 hash of it.
func Filesha512(ctx *pulumi.Context, args *Filesha512Args, opts ...pulumi.InvokeOption) (*Filesha512Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv Filesha512Result
	err := ctx.Invoke("std:index:filesha512", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type Filesha512Args struct {
	Input string `pulumi:"input"`
}

type Filesha512Result struct {
	Result string `pulumi:"result"`
}

func Filesha512Output(ctx *pulumi.Context, args Filesha512OutputArgs, opts ...pulumi.InvokeOption) Filesha512ResultOutput {
	outputResult := pulumix.ApplyErr[*Filesha512Args](args.ToOutput(), func(plainArgs *Filesha512Args) (*Filesha512Result, error) {
		return Filesha512(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[Filesha512ResultOutput, *Filesha512Result](outputResult)
}

type Filesha512OutputArgs struct {
	Input pulumix.Input[string] `pulumi:"input"`
}

func (args Filesha512OutputArgs) ToOutput() pulumix.Output[*Filesha512Args] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *Filesha512Args {
		return &Filesha512Args{
			Input: resolvedArgs[0].(string),
		}
	})
}

type Filesha512ResultOutput struct{ *pulumi.OutputState }

func (Filesha512ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Filesha512Result)(nil)).Elem()
}

func (o Filesha512ResultOutput) ToOutput(context.Context) pulumix.Output[*Filesha512Result] {
	return pulumix.Output[*Filesha512Result]{
		OutputState: o.OutputState,
	}
}

func (o Filesha512ResultOutput) Result() pulumix.Output[string] {
	return pulumix.Apply[*Filesha512Result](o, func(v *Filesha512Result) string { return v.Result })
}
