// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Returns a copy of the string with all Unicode letters mapped to their lower case.
func Lower(ctx *pulumi.Context, args *LowerArgs, opts ...pulumi.InvokeOption) (*LowerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LowerResult
	err := ctx.Invoke("std:index:lower", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LowerArgs struct {
	Input string `pulumi:"input"`
}

type LowerResult struct {
	Result string `pulumi:"result"`
}

func LowerOutput(ctx *pulumi.Context, args LowerOutputArgs, opts ...pulumi.InvokeOption) LowerResultOutput {
	outputResult := pulumix.ApplyErr[*LowerArgs](args.ToOutput(), func(plainArgs *LowerArgs) (*LowerResult, error) {
		return Lower(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[LowerResultOutput, *LowerResult](outputResult)
}

type LowerOutputArgs struct {
	Input pulumix.Input[string] `pulumi:"input"`
}

func (args LowerOutputArgs) ToOutput() pulumix.Output[*LowerArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *LowerArgs {
		return &LowerArgs{
			Input: resolvedArgs[0].(string),
		}
	})
}

type LowerResultOutput struct{ *pulumi.OutputState }

func (LowerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LowerResult)(nil)).Elem()
}

func (o LowerResultOutput) ToOutput(context.Context) pulumix.Output[*LowerResult] {
	return pulumix.Output[*LowerResult]{
		OutputState: o.OutputState,
	}
}

func (o LowerResultOutput) Result() pulumix.Output[string] {
	return pulumix.Apply[*LowerResult](o, func(v *LowerResult) string { return v.Result })
}
