// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Returns the greatest integer value less than or equal to the argument.
func Signum(ctx *pulumi.Context, args *SignumArgs, opts ...pulumi.InvokeOption) (*SignumResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv SignumResult
	err := ctx.Invoke("std:index:signum", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type SignumArgs struct {
	Input float64 `pulumi:"input"`
}

type SignumResult struct {
	Result float64 `pulumi:"result"`
}

func SignumOutput(ctx *pulumi.Context, args SignumOutputArgs, opts ...pulumi.InvokeOption) SignumResultOutput {
	outputResult := pulumix.ApplyErr[*SignumArgs](args.ToOutput(), func(plainArgs *SignumArgs) (*SignumResult, error) {
		return Signum(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[SignumResultOutput, *SignumResult](outputResult)
}

type SignumOutputArgs struct {
	Input pulumix.Input[float64] `pulumi:"input"`
}

func (args SignumOutputArgs) ToOutput() pulumix.Output[*SignumArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *SignumArgs {
		return &SignumArgs{
			Input: resolvedArgs[0].(float64),
		}
	})
}

type SignumResultOutput struct{ *pulumi.OutputState }

func (SignumResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SignumResult)(nil)).Elem()
}

func (o SignumResultOutput) ToOutput(context.Context) pulumix.Output[*SignumResult] {
	return pulumix.Output[*SignumResult]{
		OutputState: o.OutputState,
	}
}

func (o SignumResultOutput) Result() pulumix.Output[float64] {
	return pulumix.Apply[*SignumResult](o, func(v *SignumResult) float64 { return v.Result })
}
