// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Converts the first letter of each word in the given string to uppercase.
func Title(ctx *pulumi.Context, args *TitleArgs, opts ...pulumi.InvokeOption) (*TitleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv TitleResult
	err := ctx.Invoke("std:index:title", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type TitleArgs struct {
	Input string `pulumi:"input"`
}

type TitleResult struct {
	Result string `pulumi:"result"`
}

func TitleOutput(ctx *pulumi.Context, args TitleOutputArgs, opts ...pulumi.InvokeOption) TitleResultOutput {
	outputResult := pulumix.ApplyErr[*TitleArgs](args.ToOutput(), func(plainArgs *TitleArgs) (*TitleResult, error) {
		return Title(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[TitleResultOutput, *TitleResult](outputResult)
}

type TitleOutputArgs struct {
	Input pulumix.Input[string] `pulumi:"input"`
}

func (args TitleOutputArgs) ToOutput() pulumix.Output[*TitleArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *TitleArgs {
		return &TitleArgs{
			Input: resolvedArgs[0].(string),
		}
	})
}

type TitleResultOutput struct{ *pulumi.OutputState }

func (TitleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TitleResult)(nil)).Elem()
}

func (o TitleResultOutput) ToOutput(context.Context) pulumix.Output[*TitleResult] {
	return pulumix.Output[*TitleResult]{
		OutputState: o.OutputState,
	}
}

func (o TitleResultOutput) Result() pulumix.Output[string] {
	return pulumix.Apply[*TitleResult](o, func(v *TitleResult) string { return v.Result })
}
