// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-std/sdk/go/std/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Returns a list of the values of the map.
func Values(ctx *pulumi.Context, args *ValuesArgs, opts ...pulumi.InvokeOption) (*ValuesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ValuesResult
	err := ctx.Invoke("std:index:values", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ValuesArgs struct {
	Input map[string]interface{} `pulumi:"input"`
}

type ValuesResult struct {
	Result []interface{} `pulumi:"result"`
}

func ValuesOutput(ctx *pulumi.Context, args ValuesOutputArgs, opts ...pulumi.InvokeOption) ValuesResultOutput {
	outputResult := pulumix.ApplyErr[*ValuesArgs](args.ToOutput(), func(plainArgs *ValuesArgs) (*ValuesResult, error) {
		return Values(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[ValuesResultOutput, *ValuesResult](outputResult)
}

type ValuesOutputArgs struct {
	Input pulumix.Input[map[string]interface{}] `pulumi:"input"`
}

func (args ValuesOutputArgs) ToOutput() pulumix.Output[*ValuesArgs] {
	allArgs := pulumix.All(
		args.Input.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *ValuesArgs {
		return &ValuesArgs{
			Input: resolvedArgs[0].(map[string]interface{}),
		}
	})
}

type ValuesResultOutput struct{ *pulumi.OutputState }

func (ValuesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ValuesResult)(nil)).Elem()
}

func (o ValuesResultOutput) ToOutput(context.Context) pulumix.Output[*ValuesResult] {
	return pulumix.Output[*ValuesResult]{
		OutputState: o.OutputState,
	}
}

func (o ValuesResultOutput) Result() pulumix.ArrayOutput[interface{}] {
	value := pulumix.Apply[*ValuesResult](o, func(v *ValuesResult) []interface{} { return v.Result })
	return pulumix.ArrayOutput[interface{}]{
		OutputState: value.OutputState,
	}
}
