// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package std

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns a UTC timestamp string of the current time in RFC 3339 format
func Timestamp(ctx *pulumi.Context, args *TimestampArgs, opts ...pulumi.InvokeOption) (*TimestampResult, error) {
	var rv TimestampResult
	err := ctx.Invoke("std:index:timestamp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type TimestampArgs struct {
}

type TimestampResult struct {
	Result string `pulumi:"result"`
}
