run:
  timeout: 10m
linters:
  enable-all: false
  enable:
    - errcheck
    - goconst
    - gofmt
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - paralleltest
