dist: goreleaser
project_name: pulumi-std
version: 2
release:
  disable: true
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - id: pulumi-resource-std
    binary: pulumi-resource-std
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -s
      - -w
      - -X github.com/pulumi/pulumi-std/std/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-std/
    dir: std
