// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class Abspath
    {
        /// <summary>
        /// Returns an absolute representation of the specified path.
        /// If the path is not absolute it will be joined with the current working directory to turn it into an absolute path.
        /// </summary>
        public static Task<AbspathResult> InvokeAsync(AbspathArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<AbspathResult>("std:index:abspath", args ?? new AbspathArgs(), options.WithDefaults());

        /// <summary>
        /// Returns an absolute representation of the specified path.
        /// If the path is not absolute it will be joined with the current working directory to turn it into an absolute path.
        /// </summary>
        public static Output<AbspathResult> Invoke(AbspathInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<AbspathResult>("std:index:abspath", args ?? new AbspathInvokeArgs(), options.WithDefaults());
    }


    public sealed class AbspathArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public AbspathArgs()
        {
        }
        public static new AbspathArgs Empty => new AbspathArgs();
    }

    public sealed class AbspathInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public AbspathInvokeArgs()
        {
        }
        public static new AbspathInvokeArgs Empty => new AbspathInvokeArgs();
    }


    [OutputType]
    public sealed class AbspathResult
    {
        public readonly string Result;

        [OutputConstructor]
        private AbspathResult(string result)
        {
            Result = result;
        }
    }
}
