// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class Coalescelist
    {
        /// <summary>
        /// Returns the first non-empty list from the given list of lists.
        /// </summary>
        public static Task<CoalescelistResult> InvokeAsync(CoalescelistArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<CoalescelistResult>("std:index:coalescelist", args ?? new CoalescelistArgs(), options.WithDefaults());

        /// <summary>
        /// Returns the first non-empty list from the given list of lists.
        /// </summary>
        public static Output<CoalescelistResult> Invoke(CoalescelistInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<CoalescelistResult>("std:index:coalescelist", args ?? new CoalescelistInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Returns the first non-empty list from the given list of lists.
        /// </summary>
        public static Output<CoalescelistResult> Invoke(CoalescelistInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<CoalescelistResult>("std:index:coalescelist", args ?? new CoalescelistInvokeArgs(), options.WithDefaults());
    }


    public sealed class CoalescelistArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        private List<ImmutableArray<object>>? _input;
        public List<ImmutableArray<object>> Input
        {
            get => _input ?? (_input = new List<ImmutableArray<object>>());
            set => _input = value;
        }

        public CoalescelistArgs()
        {
        }
        public static new CoalescelistArgs Empty => new CoalescelistArgs();
    }

    public sealed class CoalescelistInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        private InputList<ImmutableArray<object>>? _input;
        public InputList<ImmutableArray<object>> Input
        {
            get => _input ?? (_input = new InputList<ImmutableArray<object>>());
            set => _input = value;
        }

        public CoalescelistInvokeArgs()
        {
        }
        public static new CoalescelistInvokeArgs Empty => new CoalescelistInvokeArgs();
    }


    [OutputType]
    public sealed class CoalescelistResult
    {
        public readonly ImmutableArray<object> Result;

        [OutputConstructor]
        private CoalescelistResult(ImmutableArray<object> result)
        {
            Result = result;
        }
    }
}
