// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class Filemd5
    {
        /// <summary>
        /// Reads the contents of a file into a string and returns the MD5 hash of it.
        /// </summary>
        public static Task<Filemd5Result> InvokeAsync(Filemd5Args args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Filemd5Result>("std:index:filemd5", args ?? new Filemd5Args(), options.WithDefaults());

        /// <summary>
        /// Reads the contents of a file into a string and returns the MD5 hash of it.
        /// </summary>
        public static Output<Filemd5Result> Invoke(Filemd5InvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Filemd5Result>("std:index:filemd5", args ?? new Filemd5InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Reads the contents of a file into a string and returns the MD5 hash of it.
        /// </summary>
        public static Output<Filemd5Result> Invoke(Filemd5InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<Filemd5Result>("std:index:filemd5", args ?? new Filemd5InvokeArgs(), options.WithDefaults());
    }


    public sealed class Filemd5Args : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public Filemd5Args()
        {
        }
        public static new Filemd5Args Empty => new Filemd5Args();
    }

    public sealed class Filemd5InvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public Filemd5InvokeArgs()
        {
        }
        public static new Filemd5InvokeArgs Empty => new Filemd5InvokeArgs();
    }


    [OutputType]
    public sealed class Filemd5Result
    {
        public readonly string Result;

        [OutputConstructor]
        private Filemd5Result(string result)
        {
            Result = result;
        }
    }
}
