// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class Length
    {
        /// <summary>
        /// Determines the length of a given list, map, or string.
        /// </summary>
        public static Task<LengthResult> InvokeAsync(LengthArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LengthResult>("std:index:length", args ?? new LengthArgs(), options.WithDefaults());

        /// <summary>
        /// Determines the length of a given list, map, or string.
        /// </summary>
        public static Output<LengthResult> Invoke(LengthInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LengthResult>("std:index:length", args ?? new LengthInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Determines the length of a given list, map, or string.
        /// </summary>
        public static Output<LengthResult> Invoke(LengthInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<LengthResult>("std:index:length", args ?? new LengthInvokeArgs(), options.WithDefaults());
    }


    public sealed class LengthArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public object Input { get; set; } = null!;

        public LengthArgs()
        {
        }
        public static new LengthArgs Empty => new LengthArgs();
    }

    public sealed class LengthInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<object> Input { get; set; } = null!;

        public LengthInvokeArgs()
        {
        }
        public static new LengthInvokeArgs Empty => new LengthInvokeArgs();
    }


    [OutputType]
    public sealed class LengthResult
    {
        public readonly int Result;

        [OutputConstructor]
        private LengthResult(int result)
        {
            Result = result;
        }
    }
}
