// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class Sha256
    {
        /// <summary>
        /// Returns a hexadecimal representation of the SHA-256 hash of the given string.
        /// </summary>
        public static Task<Sha256Result> InvokeAsync(Sha256Args args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Sha256Result>("std:index:sha256", args ?? new Sha256Args(), options.WithDefaults());

        /// <summary>
        /// Returns a hexadecimal representation of the SHA-256 hash of the given string.
        /// </summary>
        public static Output<Sha256Result> Invoke(Sha256InvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Sha256Result>("std:index:sha256", args ?? new Sha256InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Returns a hexadecimal representation of the SHA-256 hash of the given string.
        /// </summary>
        public static Output<Sha256Result> Invoke(Sha256InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<Sha256Result>("std:index:sha256", args ?? new Sha256InvokeArgs(), options.WithDefaults());
    }


    public sealed class Sha256Args : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public Sha256Args()
        {
        }
        public static new Sha256Args Empty => new Sha256Args();
    }

    public sealed class Sha256InvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public Sha256InvokeArgs()
        {
        }
        public static new Sha256InvokeArgs Empty => new Sha256InvokeArgs();
    }


    [OutputType]
    public sealed class Sha256Result
    {
        public readonly string Result;

        [OutputConstructor]
        private Sha256Result(string result)
        {
            Result = result;
        }
    }
}
