// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class TrimSuffix
    {
        /// <summary>
        /// Removes the specified suffix from the end of the given string, if present.
        /// </summary>
        public static Task<TrimSuffixResult> InvokeAsync(TrimSuffixArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<TrimSuffixResult>("std:index:trimSuffix", args ?? new TrimSuffixArgs(), options.WithDefaults());

        /// <summary>
        /// Removes the specified suffix from the end of the given string, if present.
        /// </summary>
        public static Output<TrimSuffixResult> Invoke(TrimSuffixInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<TrimSuffixResult>("std:index:trimSuffix", args ?? new TrimSuffixInvokeArgs(), options.WithDefaults());
    }


    public sealed class TrimSuffixArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        [Input("suffix", required: true)]
        public string Suffix { get; set; } = null!;

        public TrimSuffixArgs()
        {
        }
        public static new TrimSuffixArgs Empty => new TrimSuffixArgs();
    }

    public sealed class TrimSuffixInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        [Input("suffix", required: true)]
        public Input<string> Suffix { get; set; } = null!;

        public TrimSuffixInvokeArgs()
        {
        }
        public static new TrimSuffixInvokeArgs Empty => new TrimSuffixInvokeArgs();
    }


    [OutputType]
    public sealed class TrimSuffixResult
    {
        public readonly string Result;

        [OutputConstructor]
        private TrimSuffixResult(string result)
        {
            Result = result;
        }
    }
}
