// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class TrimSpace
    {
        /// <summary>
        /// Removes any space characters from the start and end of the given string,
        /// 	following the Unicode definition of \"space\" (i.e. spaces, tabs, newline, etc.).
        /// </summary>
        public static Task<TrimSpaceResult> InvokeAsync(TrimSpaceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<TrimSpaceResult>("std:index:trimSpace", args ?? new TrimSpaceArgs(), options.WithDefaults());

        /// <summary>
        /// Removes any space characters from the start and end of the given string,
        /// 	following the Unicode definition of \"space\" (i.e. spaces, tabs, newline, etc.).
        /// </summary>
        public static Output<TrimSpaceResult> Invoke(TrimSpaceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<TrimSpaceResult>("std:index:trimSpace", args ?? new TrimSpaceInvokeArgs(), options.WithDefaults());
    }


    public sealed class TrimSpaceArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public TrimSpaceArgs()
        {
        }
        public static new TrimSpaceArgs Empty => new TrimSpaceArgs();
    }

    public sealed class TrimSpaceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public TrimSpaceInvokeArgs()
        {
        }
        public static new TrimSpaceInvokeArgs Empty => new TrimSpaceInvokeArgs();
    }


    [OutputType]
    public sealed class TrimSpaceResult
    {
        public readonly string Result;

        [OutputConstructor]
        private TrimSpaceResult(string result)
        {
            Result = result;
        }
    }
}
