// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Std
{
    public static class UrlEncode
    {
        /// <summary>
        /// Applies URL encoding to a given string.
        /// </summary>
        public static Task<UrlEncodeResult> InvokeAsync(UrlEncodeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<UrlEncodeResult>("std:index:urlEncode", args ?? new UrlEncodeArgs(), options.WithDefaults());

        /// <summary>
        /// Applies URL encoding to a given string.
        /// </summary>
        public static Output<UrlEncodeResult> Invoke(UrlEncodeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<UrlEncodeResult>("std:index:urlEncode", args ?? new UrlEncodeInvokeArgs(), options.WithDefaults());
    }


    public sealed class UrlEncodeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public UrlEncodeArgs()
        {
        }
        public static new UrlEncodeArgs Empty => new UrlEncodeArgs();
    }

    public sealed class UrlEncodeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public UrlEncodeInvokeArgs()
        {
        }
        public static new UrlEncodeInvokeArgs Empty => new UrlEncodeInvokeArgs();
    }


    [OutputType]
    public sealed class UrlEncodeResult
    {
        public readonly string Result;

        [OutputConstructor]
        private UrlEncodeResult(string result)
        {
            Result = result;
        }
    }
}
