# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'Filebase64sha256Result',
    'AwaitableFilebase64sha256Result',
    'filebase64sha256',
    'filebase64sha256_output',
]

@pulumi.output_type
class Filebase64sha256Result:
    def __init__(__self__, result=None):
        if result and not isinstance(result, str):
            raise TypeError("Expected argument 'result' to be a str")
        pulumi.set(__self__, "result", result)

    @_builtins.property
    @pulumi.getter
    def result(self) -> _builtins.str:
        return pulumi.get(self, "result")


class AwaitableFilebase64sha256Result(Filebase64sha256Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return Filebase64sha256Result(
            result=self.result)


def filebase64sha256(input: Optional[_builtins.str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableFilebase64sha256Result:
    """
    Reads the contents of a file into a string and returns the base64-encoded SHA256 hash of it.
    """
    __args__ = dict()
    __args__['input'] = input
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:filebase64sha256', __args__, opts=opts, typ=Filebase64sha256Result).value

    return AwaitableFilebase64sha256Result(
        result=pulumi.get(__ret__, 'result'))
def filebase64sha256_output(input: Optional[pulumi.Input[_builtins.str]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[Filebase64sha256Result]:
    """
    Reads the contents of a file into a string and returns the base64-encoded SHA256 hash of it.
    """
    __args__ = dict()
    __args__['input'] = input
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('std:index:filebase64sha256', __args__, opts=opts, typ=Filebase64sha256Result)
    return __ret__.apply(lambda __response__: Filebase64sha256Result(
        result=pulumi.get(__response__, 'result')))
