# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'LogResult',
    'AwaitableLogResult',
    'log',
    'log_output',
]

@pulumi.output_type
class LogResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, float):
            raise TypeError("Expected argument 'result' to be a float")
        pulumi.set(__self__, "result", result)

    @property
    @pulumi.getter
    def result(self) -> float:
        return pulumi.get(self, "result")


class AwaitableLogResult(LogResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return LogResult(
            result=self.result)


def log(base: Optional[float] = None,
        input: Optional[float] = None,
        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableLogResult:
    """
    Returns the greatest integer value less than or equal to the argument.
    """
    __args__ = dict()
    __args__['base'] = base
    __args__['input'] = input
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:log', __args__, opts=opts, typ=LogResult).value

    return AwaitableLogResult(
        result=pulumi.get(__ret__, 'result'))


@_utilities.lift_output_func(log)
def log_output(base: Optional[pulumi.Input[float]] = None,
               input: Optional[pulumi.Input[float]] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[LogResult]:
    """
    Returns the greatest integer value less than or equal to the argument.
    """
    ...
