# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'MatchkeysResult',
    'AwaitableMatchkeysResult',
    'matchkeys',
    'matchkeys_output',
]

@pulumi.output_type
class MatchkeysResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, list):
            raise TypeError("Expected argument 'result' to be a list")
        pulumi.set(__self__, "result", result)

    @_builtins.property
    @pulumi.getter
    def result(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "result")


class AwaitableMatchkeysResult(MatchkeysResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return MatchkeysResult(
            result=self.result)


def matchkeys(search_list: Optional[Sequence[_builtins.str]] = None,
              values: Optional[Sequence[_builtins.str]] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableMatchkeysResult:
    """
    For two lists values and keys of equal length,
    returns all elements from values where the corresponding element from keys exists in the searchset list.
    """
    __args__ = dict()
    __args__['searchList'] = search_list
    __args__['values'] = values
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:matchkeys', __args__, opts=opts, typ=MatchkeysResult).value

    return AwaitableMatchkeysResult(
        result=pulumi.get(__ret__, 'result'))
def matchkeys_output(search_list: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                     values: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[MatchkeysResult]:
    """
    For two lists values and keys of equal length,
    returns all elements from values where the corresponding element from keys exists in the searchset list.
    """
    __args__ = dict()
    __args__['searchList'] = search_list
    __args__['values'] = values
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('std:index:matchkeys', __args__, opts=opts, typ=MatchkeysResult)
    return __ret__.apply(lambda __response__: MatchkeysResult(
        result=pulumi.get(__response__, 'result')))
