# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'MergeResult',
    'AwaitableMergeResult',
    'merge',
    'merge_output',
]

@pulumi.output_type
class MergeResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, dict):
            raise TypeError("Expected argument 'result' to be a dict")
        pulumi.set(__self__, "result", result)

    @property
    @pulumi.getter
    def result(self) -> Mapping[str, Any]:
        return pulumi.get(self, "result")


class AwaitableMergeResult(MergeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return MergeResult(
            result=self.result)


def merge(input: Optional[Sequence[Mapping[str, Any]]] = None,
          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableMergeResult:
    """
    Returns the union of 2 or more maps. The maps are consumed in the order provided,
    and duplicate keys overwrite previous entries.
    """
    __args__ = dict()
    __args__['input'] = input
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:merge', __args__, opts=opts, typ=MergeResult).value

    return AwaitableMergeResult(
        result=pulumi.get(__ret__, 'result'))


@_utilities.lift_output_func(merge)
def merge_output(input: Optional[pulumi.Input[Sequence[Mapping[str, Any]]]] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[MergeResult]:
    """
    Returns the union of 2 or more maps. The maps are consumed in the order provided,
    and duplicate keys overwrite previous entries.
    """
    ...
