# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TosetResult',
    'AwaitableTosetResult',
    'toset',
    'toset_output',
]

@pulumi.output_type
class TosetResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, list):
            raise TypeError("Expected argument 'result' to be a list")
        pulumi.set(__self__, "result", result)

    @property
    @pulumi.getter
    def result(self) -> Sequence[Any]:
        return pulumi.get(self, "result")


class AwaitableTosetResult(TosetResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return TosetResult(
            result=self.result)


def toset(input: Optional[Sequence[Any]] = None,
          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableTosetResult:
    """
    Converts its argument to a set value.
    """
    __args__ = dict()
    __args__['input'] = input
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:toset', __args__, opts=opts, typ=TosetResult).value

    return AwaitableTosetResult(
        result=pulumi.get(__ret__, 'result'))


@_utilities.lift_output_func(toset)
def toset_output(input: Optional[pulumi.Input[Sequence[Any]]] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[TosetResult]:
    """
    Converts its argument to a set value.
    """
    ...
