# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'Unixtorfc3999Result',
    'AwaitableUnixtorfc3999Result',
    'unixtorfc3999',
    'unixtorfc3999_output',
]

@pulumi.output_type
class Unixtorfc3999Result:
    def __init__(__self__, result=None):
        if result and not isinstance(result, int):
            raise TypeError("Expected argument 'result' to be a int")
        pulumi.set(__self__, "result", result)

    @property
    @pulumi.getter
    def result(self) -> int:
        return pulumi.get(self, "result")


class AwaitableUnixtorfc3999Result(Unixtorfc3999Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return Unixtorfc3999Result(
            result=self.result)


def unixtorfc3999(input: Optional[str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableUnixtorfc3999Result:
    """
    Converts a RFC3999 formatted timestamp into a Unix timestamp with milliseconds.
    """
    __args__ = dict()
    __args__['input'] = input
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('std:index:unixtorfc3999', __args__, opts=opts, typ=Unixtorfc3999Result).value

    return AwaitableUnixtorfc3999Result(
        result=pulumi.get(__ret__, 'result'))


@_utilities.lift_output_func(unixtorfc3999)
def unixtorfc3999_output(input: Optional[pulumi.Input[str]] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[Unixtorfc3999Result]:
    """
    Converts a RFC3999 formatted timestamp into a Unix timestamp with milliseconds.
    """
    ...
