// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class CsvdecodeResult {
    private List<Map<String,String>> result;

    private CsvdecodeResult() {}
    public List<Map<String,String>> result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CsvdecodeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<Map<String,String>> result;
        public Builder() {}
        public Builder(CsvdecodeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.result = defaults.result;
        }

        @CustomType.Setter
        public Builder result(List<Map<String,String>> result) {
            this.result = Objects.requireNonNull(result);
            return this;
        }
        public CsvdecodeResult build() {
            final var o = new CsvdecodeResult();
            o.result = result;
            return o;
        }
    }
}
