// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.util.Objects;

@CustomType
public final class JsondecodeResult {
    private Object result;

    private JsondecodeResult() {}
    public Object result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(JsondecodeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Object result;
        public Builder() {}
        public Builder(JsondecodeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.result = defaults.result;
        }

        @CustomType.Setter
        public Builder result(Object result) {
            if (result == null) {
              throw new MissingRequiredPropertyException("JsondecodeResult", "result");
            }
            this.result = result;
            return this;
        }
        public JsondecodeResult build() {
            final var _resultValue = new JsondecodeResult();
            _resultValue.result = result;
            return _resultValue;
        }
    }
}
