// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class KeysResult {
    private List<String> result;

    private KeysResult() {}
    public List<String> result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KeysResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> result;
        public Builder() {}
        public Builder(KeysResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.result = defaults.result;
        }

        @CustomType.Setter
        public Builder result(List<String> result) {
            if (result == null) {
              throw new MissingRequiredPropertyException("KeysResult", "result");
            }
            this.result = result;
            return this;
        }
        public Builder result(String... result) {
            return result(List.of(result));
        }
        public KeysResult build() {
            final var _resultValue = new KeysResult();
            _resultValue.result = result;
            return _resultValue;
        }
    }
}
