// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class StartswithResult {
    private Boolean result;

    private StartswithResult() {}
    public Boolean result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StartswithResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean result;
        public Builder() {}
        public Builder(StartswithResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.result = defaults.result;
        }

        @CustomType.Setter
        public Builder result(Boolean result) {
            this.result = Objects.requireNonNull(result);
            return this;
        }
        public StartswithResult build() {
            final var o = new StartswithResult();
            o.result = result;
            return o;
        }
    }
}
