// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class ZipmapResult {
    private Map<String,Object> result;

    private ZipmapResult() {}
    public Map<String,Object> result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ZipmapResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,Object> result;
        public Builder() {}
        public Builder(ZipmapResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.result = defaults.result;
        }

        @CustomType.Setter
        public Builder result(Map<String,Object> result) {
            if (result == null) {
              throw new MissingRequiredPropertyException("ZipmapResult", "result");
            }
            this.result = result;
            return this;
        }
        public ZipmapResult build() {
            final var _resultValue = new ZipmapResult();
            _resultValue.result = result;
            return _resultValue;
        }
    }
}
