// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AbspathPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final AbspathPlainArgs Empty = new AbspathPlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private AbspathPlainArgs() {}

    private AbspathPlainArgs(AbspathPlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AbspathPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AbspathPlainArgs $;

        public Builder() {
            $ = new AbspathPlainArgs();
        }

        public Builder(AbspathPlainArgs defaults) {
            $ = new AbspathPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public AbspathPlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("AbspathPlainArgs", "input");
            }
            return $;
        }
    }

}
