// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Object;
import java.util.List;
import java.util.Objects;


public final class AlltrueArgs extends com.pulumi.resources.InvokeArgs {

    public static final AlltrueArgs Empty = new AlltrueArgs();

    @Import(name="input", required=true)
    private Output<List<Object>> input;

    public Output<List<Object>> input() {
        return this.input;
    }

    private AlltrueArgs() {}

    private AlltrueArgs(AlltrueArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AlltrueArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AlltrueArgs $;

        public Builder() {
            $ = new AlltrueArgs();
        }

        public Builder(AlltrueArgs defaults) {
            $ = new AlltrueArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(Output<List<Object>> input) {
            $.input = input;
            return this;
        }

        public Builder input(List<Object> input) {
            return input(Output.of(input));
        }

        public Builder input(Object... input) {
            return input(List.of(input));
        }

        public AlltrueArgs build() {
            $.input = Objects.requireNonNull($.input, "expected parameter 'input' to be non-null");
            return $;
        }
    }

}
