// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class Base64decodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final Base64decodePlainArgs Empty = new Base64decodePlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private Base64decodePlainArgs() {}

    private Base64decodePlainArgs(Base64decodePlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(Base64decodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Base64decodePlainArgs $;

        public Builder() {
            $ = new Base64decodePlainArgs();
        }

        public Builder(Base64decodePlainArgs defaults) {
            $ = new Base64decodePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public Base64decodePlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("Base64decodePlainArgs", "input");
            }
            return $;
        }
    }

}
