// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class Base64sha512PlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final Base64sha512PlainArgs Empty = new Base64sha512PlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private Base64sha512PlainArgs() {}

    private Base64sha512PlainArgs(Base64sha512PlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(Base64sha512PlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Base64sha512PlainArgs $;

        public Builder() {
            $ = new Base64sha512PlainArgs();
        }

        public Builder(Base64sha512PlainArgs defaults) {
            $ = new Base64sha512PlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public Base64sha512PlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("Base64sha512PlainArgs", "input");
            }
            return $;
        }
    }

}
