// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BcryptArgs extends com.pulumi.resources.InvokeArgs {

    public static final BcryptArgs Empty = new BcryptArgs();

    @Import(name="cost")
    private @Nullable Output<Integer> cost;

    public Optional<Output<Integer>> cost() {
        return Optional.ofNullable(this.cost);
    }

    @Import(name="input", required=true)
    private Output<String> input;

    public Output<String> input() {
        return this.input;
    }

    private BcryptArgs() {}

    private BcryptArgs(BcryptArgs $) {
        this.cost = $.cost;
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BcryptArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BcryptArgs $;

        public Builder() {
            $ = new BcryptArgs();
        }

        public Builder(BcryptArgs defaults) {
            $ = new BcryptArgs(Objects.requireNonNull(defaults));
        }

        public Builder cost(@Nullable Output<Integer> cost) {
            $.cost = cost;
            return this;
        }

        public Builder cost(Integer cost) {
            return cost(Output.of(cost));
        }

        public Builder input(Output<String> input) {
            $.input = input;
            return this;
        }

        public Builder input(String input) {
            return input(Output.of(input));
        }

        public BcryptArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("BcryptArgs", "input");
            }
            return $;
        }
    }

}
