// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class ChompPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final ChompPlainArgs Empty = new ChompPlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private ChompPlainArgs() {}

    private ChompPlainArgs(ChompPlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ChompPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ChompPlainArgs $;

        public Builder() {
            $ = new ChompPlainArgs();
        }

        public Builder(ChompPlainArgs defaults) {
            $ = new ChompPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public ChompPlainArgs build() {
            $.input = Objects.requireNonNull($.input, "expected parameter 'input' to be non-null");
            return $;
        }
    }

}
