// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class CidrsubnetsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final CidrsubnetsPlainArgs Empty = new CidrsubnetsPlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    @Import(name="newbits", required=true)
    private List<Integer> newbits;

    public List<Integer> newbits() {
        return this.newbits;
    }

    private CidrsubnetsPlainArgs() {}

    private CidrsubnetsPlainArgs(CidrsubnetsPlainArgs $) {
        this.input = $.input;
        this.newbits = $.newbits;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CidrsubnetsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CidrsubnetsPlainArgs $;

        public Builder() {
            $ = new CidrsubnetsPlainArgs();
        }

        public Builder(CidrsubnetsPlainArgs defaults) {
            $ = new CidrsubnetsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public Builder newbits(List<Integer> newbits) {
            $.newbits = newbits;
            return this;
        }

        public Builder newbits(Integer... newbits) {
            return newbits(List.of(newbits));
        }

        public CidrsubnetsPlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("CidrsubnetsPlainArgs", "input");
            }
            if ($.newbits == null) {
                throw new MissingRequiredPropertyException("CidrsubnetsPlainArgs", "newbits");
            }
            return $;
        }
    }

}
