// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class Filebase64PlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final Filebase64PlainArgs Empty = new Filebase64PlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private Filebase64PlainArgs() {}

    private Filebase64PlainArgs(Filebase64PlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(Filebase64PlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Filebase64PlainArgs $;

        public Builder() {
            $ = new Filebase64PlainArgs();
        }

        public Builder(Filebase64PlainArgs defaults) {
            $ = new Filebase64PlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public Filebase64PlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("Filebase64PlainArgs", "input");
            }
            return $;
        }
    }

}
