// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class IndentArgs extends com.pulumi.resources.InvokeArgs {

    public static final IndentArgs Empty = new IndentArgs();

    @Import(name="input", required=true)
    private Output<String> input;

    public Output<String> input() {
        return this.input;
    }

    @Import(name="spaces", required=true)
    private Output<Integer> spaces;

    public Output<Integer> spaces() {
        return this.spaces;
    }

    private IndentArgs() {}

    private IndentArgs(IndentArgs $) {
        this.input = $.input;
        this.spaces = $.spaces;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IndentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IndentArgs $;

        public Builder() {
            $ = new IndentArgs();
        }

        public Builder(IndentArgs defaults) {
            $ = new IndentArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(Output<String> input) {
            $.input = input;
            return this;
        }

        public Builder input(String input) {
            return input(Output.of(input));
        }

        public Builder spaces(Output<Integer> spaces) {
            $.spaces = spaces;
            return this;
        }

        public Builder spaces(Integer spaces) {
            return spaces(Output.of(spaces));
        }

        public IndentArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("IndentArgs", "input");
            }
            if ($.spaces == null) {
                throw new MissingRequiredPropertyException("IndentArgs", "spaces");
            }
            return $;
        }
    }

}
