// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.util.Objects;


public final class PowArgs extends com.pulumi.resources.InvokeArgs {

    public static final PowArgs Empty = new PowArgs();

    @Import(name="base", required=true)
    private Output<Double> base;

    public Output<Double> base() {
        return this.base;
    }

    @Import(name="exponent", required=true)
    private Output<Double> exponent;

    public Output<Double> exponent() {
        return this.exponent;
    }

    private PowArgs() {}

    private PowArgs(PowArgs $) {
        this.base = $.base;
        this.exponent = $.exponent;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PowArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PowArgs $;

        public Builder() {
            $ = new PowArgs();
        }

        public Builder(PowArgs defaults) {
            $ = new PowArgs(Objects.requireNonNull(defaults));
        }

        public Builder base(Output<Double> base) {
            $.base = base;
            return this;
        }

        public Builder base(Double base) {
            return base(Output.of(base));
        }

        public Builder exponent(Output<Double> exponent) {
            $.exponent = exponent;
            return this;
        }

        public Builder exponent(Double exponent) {
            return exponent(Output.of(exponent));
        }

        public PowArgs build() {
            $.base = Objects.requireNonNull($.base, "expected parameter 'base' to be non-null");
            $.exponent = Objects.requireNonNull($.exponent, "expected parameter 'exponent' to be non-null");
            return $;
        }
    }

}
