// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.util.List;
import java.util.Objects;


public final class ReverseArgs extends com.pulumi.resources.InvokeArgs {

    public static final ReverseArgs Empty = new ReverseArgs();

    @Import(name="input", required=true)
    private Output<List<Object>> input;

    public Output<List<Object>> input() {
        return this.input;
    }

    private ReverseArgs() {}

    private ReverseArgs(ReverseArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ReverseArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ReverseArgs $;

        public Builder() {
            $ = new ReverseArgs();
        }

        public Builder(ReverseArgs defaults) {
            $ = new ReverseArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(Output<List<Object>> input) {
            $.input = input;
            return this;
        }

        public Builder input(List<Object> input) {
            return input(Output.of(input));
        }

        public Builder input(Object... input) {
            return input(List.of(input));
        }

        public ReverseArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("ReverseArgs", "input");
            }
            return $;
        }
    }

}
