// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class StrrevArgs extends com.pulumi.resources.InvokeArgs {

    public static final StrrevArgs Empty = new StrrevArgs();

    @Import(name="input", required=true)
    private Output<String> input;

    public Output<String> input() {
        return this.input;
    }

    private StrrevArgs() {}

    private StrrevArgs(StrrevArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(StrrevArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StrrevArgs $;

        public Builder() {
            $ = new StrrevArgs();
        }

        public Builder(StrrevArgs defaults) {
            $ = new StrrevArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(Output<String> input) {
            $.input = input;
            return this;
        }

        public Builder input(String input) {
            return input(Output.of(input));
        }

        public StrrevArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("StrrevArgs", "input");
            }
            return $;
        }
    }

}
