// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class SubstrPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final SubstrPlainArgs Empty = new SubstrPlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    @Import(name="length", required=true)
    private Integer length;

    public Integer length() {
        return this.length;
    }

    @Import(name="offset", required=true)
    private Integer offset;

    public Integer offset() {
        return this.offset;
    }

    private SubstrPlainArgs() {}

    private SubstrPlainArgs(SubstrPlainArgs $) {
        this.input = $.input;
        this.length = $.length;
        this.offset = $.offset;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SubstrPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SubstrPlainArgs $;

        public Builder() {
            $ = new SubstrPlainArgs();
        }

        public Builder(SubstrPlainArgs defaults) {
            $ = new SubstrPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public Builder length(Integer length) {
            $.length = length;
            return this;
        }

        public Builder offset(Integer offset) {
            $.offset = offset;
            return this;
        }

        public SubstrPlainArgs build() {
            $.input = Objects.requireNonNull($.input, "expected parameter 'input' to be non-null");
            $.length = Objects.requireNonNull($.length, "expected parameter 'length' to be non-null");
            $.offset = Objects.requireNonNull($.offset, "expected parameter 'offset' to be non-null");
            return $;
        }
    }

}
