// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.util.List;
import java.util.Objects;


public final class SumPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final SumPlainArgs Empty = new SumPlainArgs();

    @Import(name="input", required=true)
    private List<Double> input;

    public List<Double> input() {
        return this.input;
    }

    private SumPlainArgs() {}

    private SumPlainArgs(SumPlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SumPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SumPlainArgs $;

        public Builder() {
            $ = new SumPlainArgs();
        }

        public Builder(SumPlainArgs defaults) {
            $ = new SumPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(List<Double> input) {
            $.input = input;
            return this;
        }

        public Builder input(Double... input) {
            return input(List.of(input));
        }

        public SumPlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("SumPlainArgs", "input");
            }
            return $;
        }
    }

}
