// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;




public final class TimestampPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final TimestampPlainArgs Empty = new TimestampPlainArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private TimestampPlainArgs $;

        public Builder() {
            $ = new TimestampPlainArgs();
        }
        public TimestampPlainArgs build() {
            return $;
        }
    }

}
