// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class TimeaddPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final TimeaddPlainArgs Empty = new TimeaddPlainArgs();

    @Import(name="duration", required=true)
    private String duration;

    public String duration() {
        return this.duration;
    }

    @Import(name="timestamp", required=true)
    private String timestamp;

    public String timestamp() {
        return this.timestamp;
    }

    private TimeaddPlainArgs() {}

    private TimeaddPlainArgs(TimeaddPlainArgs $) {
        this.duration = $.duration;
        this.timestamp = $.timestamp;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TimeaddPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TimeaddPlainArgs $;

        public Builder() {
            $ = new TimeaddPlainArgs();
        }

        public Builder(TimeaddPlainArgs defaults) {
            $ = new TimeaddPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder duration(String duration) {
            $.duration = duration;
            return this;
        }

        public Builder timestamp(String timestamp) {
            $.timestamp = timestamp;
            return this;
        }

        public TimeaddPlainArgs build() {
            if ($.duration == null) {
                throw new MissingRequiredPropertyException("TimeaddPlainArgs", "duration");
            }
            if ($.timestamp == null) {
                throw new MissingRequiredPropertyException("TimeaddPlainArgs", "timestamp");
            }
            return $;
        }
    }

}
