// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class TitlePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final TitlePlainArgs Empty = new TitlePlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private TitlePlainArgs() {}

    private TitlePlainArgs(TitlePlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TitlePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TitlePlainArgs $;

        public Builder() {
            $ = new TitlePlainArgs();
        }

        public Builder(TitlePlainArgs defaults) {
            $ = new TitlePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public TitlePlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("TitlePlainArgs", "input");
            }
            return $;
        }
    }

}
