// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.std.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class UrlencodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final UrlencodePlainArgs Empty = new UrlencodePlainArgs();

    @Import(name="input", required=true)
    private String input;

    public String input() {
        return this.input;
    }

    private UrlencodePlainArgs() {}

    private UrlencodePlainArgs(UrlencodePlainArgs $) {
        this.input = $.input;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UrlencodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UrlencodePlainArgs $;

        public Builder() {
            $ = new UrlencodePlainArgs();
        }

        public Builder(UrlencodePlainArgs defaults) {
            $ = new UrlencodePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder input(String input) {
            $.input = input;
            return this;
        }

        public UrlencodePlainArgs build() {
            if ($.input == null) {
                throw new MissingRequiredPropertyException("UrlencodePlainArgs", "input");
            }
            return $;
        }
    }

}
