// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Removes one or more newline characters from the end of the given string.
 */
export function chomp(args: ChompArgs, opts?: pulumi.InvokeOptions): Promise<ChompResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:chomp", {
        "input": args.input,
    }, opts);
}

export interface ChompArgs {
    input: string;
}

export interface ChompResult {
    readonly result: string;
}
/**
 * Removes one or more newline characters from the end of the given string.
 */
export function chompOutput(args: ChompOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ChompResult> {
    return pulumi.output(args).apply((a: any) => chomp(a, opts))
}

export interface ChompOutputArgs {
    input: pulumi.Input<string>;
}
