// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Removes duplicate items from a list.
 */
export function distinct(args: DistinctArgs, opts?: pulumi.InvokeOptions): Promise<DistinctResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:distinct", {
        "input": args.input,
    }, opts);
}

export interface DistinctArgs {
    input: any[];
}

export interface DistinctResult {
    readonly result: any[];
}
/**
 * Removes duplicate items from a list.
 */
export function distinctOutput(args: DistinctOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<DistinctResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("std:index:distinct", {
        "input": args.input,
    }, opts);
}

export interface DistinctOutputArgs {
    input: pulumi.Input<any[]>;
}
