// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Finds the index of a given element in a list.
 */
export function index(args: IndexArgs, opts?: pulumi.InvokeOptions): Promise<IndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:index", {
        "element": args.element,
        "input": args.input,
    }, opts);
}

export interface IndexArgs {
    element: any;
    input: any[];
}

export interface IndexResult {
    readonly result: number;
}
/**
 * Finds the index of a given element in a list.
 */
export function indexOutput(args: IndexOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<IndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("std:index:index", {
        "element": args.element,
        "input": args.input,
    }, opts);
}

export interface IndexOutputArgs {
    element: any;
    input: pulumi.Input<any[]>;
}
