// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns a copy of the string with all Unicode letters mapped to their lower case.
 */
export function lower(args: LowerArgs, opts?: pulumi.InvokeOptions): Promise<LowerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:lower", {
        "input": args.input,
    }, opts);
}

export interface LowerArgs {
    input: string;
}

export interface LowerResult {
    readonly result: string;
}
/**
 * Returns a copy of the string with all Unicode letters mapped to their lower case.
 */
export function lowerOutput(args: LowerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<LowerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("std:index:lower", {
        "input": args.input,
    }, opts);
}

export interface LowerOutputArgs {
    input: pulumi.Input<string>;
}
