// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns the largest of the floats.
 */
export function max(args: MaxArgs, opts?: pulumi.InvokeOptions): Promise<MaxResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("std:index:max", {
        "input": args.input,
    }, opts);
}

export interface MaxArgs {
    input: number[];
}

export interface MaxResult {
    readonly result: number;
}

export function maxOutput(args: MaxOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<MaxResult> {
    return pulumi.output(args).apply(a => max(a, opts))
}

export interface MaxOutputArgs {
    input: pulumi.Input<pulumi.Input<number>[]>;
}
