// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns a (conventional) hexadecimal representation of the MD5 hash of the given string.
 */
export function md5(args: Md5Args, opts?: pulumi.InvokeOptions): Promise<Md5Result> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:md5", {
        "input": args.input,
    }, opts);
}

export interface Md5Args {
    input: string;
}

export interface Md5Result {
    readonly result: string;
}
/**
 * Returns a (conventional) hexadecimal representation of the MD5 hash of the given string.
 */
export function md5Output(args: Md5OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<Md5Result> {
    return pulumi.output(args).apply((a: any) => md5(a, opts))
}

export interface Md5OutputArgs {
    input: pulumi.Input<string>;
}
