// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns a hexadecimal representation of the SHA-1 hash of the given string.
 */
export function sha1(args: Sha1Args, opts?: pulumi.InvokeOptions): Promise<Sha1Result> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("std:index:sha1", {
        "input": args.input,
    }, opts);
}

export interface Sha1Args {
    input: string;
}

export interface Sha1Result {
    readonly result: string;
}

export function sha1Output(args: Sha1OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<Sha1Result> {
    return pulumi.output(args).apply(a => sha1(a, opts))
}

export interface Sha1OutputArgs {
    input: pulumi.Input<string>;
}
