// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns a hexadecimal representation of the SHA-256 hash of the given string.
 */
export function sha256(args: Sha256Args, opts?: pulumi.InvokeOptions): Promise<Sha256Result> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:sha256", {
        "input": args.input,
    }, opts);
}

export interface Sha256Args {
    input: string;
}

export interface Sha256Result {
    readonly result: string;
}
/**
 * Returns a hexadecimal representation of the SHA-256 hash of the given string.
 */
export function sha256Output(args: Sha256OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<Sha256Result> {
    return pulumi.output(args).apply((a: any) => sha256(a, opts))
}

export interface Sha256OutputArgs {
    input: pulumi.Input<string>;
}
