// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns the greatest integer value less than or equal to the argument.
 */
export function signum(args: SignumArgs, opts?: pulumi.InvokeOptions): Promise<SignumResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:signum", {
        "input": args.input,
    }, opts);
}

export interface SignumArgs {
    input: number;
}

export interface SignumResult {
    readonly result: number;
}
/**
 * Returns the greatest integer value less than or equal to the argument.
 */
export function signumOutput(args: SignumOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SignumResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("std:index:signum", {
        "input": args.input,
    }, opts);
}

export interface SignumOutputArgs {
    input: pulumi.Input<number>;
}
