// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Removes the specified suffix from the end of the given string, if present.
 */
export function trimsuffix(args: TrimsuffixArgs, opts?: pulumi.InvokeOptions): Promise<TrimsuffixResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:trimsuffix", {
        "input": args.input,
        "suffix": args.suffix,
    }, opts);
}

export interface TrimsuffixArgs {
    input: string;
    suffix: string;
}

export interface TrimsuffixResult {
    readonly result: string;
}
/**
 * Removes the specified suffix from the end of the given string, if present.
 */
export function trimsuffixOutput(args: TrimsuffixOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<TrimsuffixResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("std:index:trimsuffix", {
        "input": args.input,
        "suffix": args.suffix,
    }, opts);
}

export interface TrimsuffixOutputArgs {
    input: pulumi.Input<string>;
    suffix: pulumi.Input<string>;
}
