// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Converts a RFC3999 formatted timestamp into a Unix timestamp with milliseconds.
 */
export function unixtorfc3999(args: Unixtorfc3999Args, opts?: pulumi.InvokeOptions): Promise<Unixtorfc3999Result> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:unixtorfc3999", {
        "input": args.input,
    }, opts);
}

export interface Unixtorfc3999Args {
    input: string;
}

export interface Unixtorfc3999Result {
    readonly result: number;
}
/**
 * Converts a RFC3999 formatted timestamp into a Unix timestamp with milliseconds.
 */
export function unixtorfc3999Output(args: Unixtorfc3999OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<Unixtorfc3999Result> {
    return pulumi.output(args).apply((a: any) => unixtorfc3999(a, opts))
}

export interface Unixtorfc3999OutputArgs {
    input: pulumi.Input<string>;
}
