// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Applies URL encoding to a given string.
 */
export function urlencode(args: UrlencodeArgs, opts?: pulumi.InvokeOptions): Promise<UrlencodeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:urlencode", {
        "input": args.input,
    }, opts);
}

export interface UrlencodeArgs {
    input: string;
}

export interface UrlencodeResult {
    readonly result: string;
}
/**
 * Applies URL encoding to a given string.
 */
export function urlencodeOutput(args: UrlencodeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<UrlencodeResult> {
    return pulumi.output(args).apply((a: any) => urlencode(a, opts))
}

export interface UrlencodeOutputArgs {
    input: pulumi.Input<string>;
}
