// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns a list of the values of the map.
 */
export function values(args: ValuesArgs, opts?: pulumi.InvokeOptions): Promise<ValuesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("std:index:values", {
        "input": args.input,
    }, opts);
}

export interface ValuesArgs {
    input: {[key: string]: any};
}

export interface ValuesResult {
    readonly result: any[];
}
/**
 * Returns a list of the values of the map.
 */
export function valuesOutput(args: ValuesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ValuesResult> {
    return pulumi.output(args).apply((a: any) => values(a, opts))
}

export interface ValuesOutputArgs {
    input: pulumi.Input<{[key: string]: any}>;
}
